service: coin-limit-trader

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
       - lambda:InvokeFunction
      Resource: arn:aws:lambda:us-east-1:${env:AWS_ACCOUNT_ID}:function:coin-limit-trader-prod-trade
  

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamic-dotenv
  - serverless-offline-sns

functions:
  trade:
    handler: src/handlers/trade-api.trade
    timeout: 300
    events:
      - http:
          path: trade
          method: post

custom:
  serverless-offline-sns:
    port: 4002
    debug: true