service: coin-limit-trader

stage: prod
region: us-west-2

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts

functions:
  trade:
    handler: src/trade-api.trade

    events:
      - http:
          path: trade
          method: post

  trade-scheduler:
      handler: src/trade-scheduler.trade

      events:
        - http:
            path: trade
            method: post
