service: coin-limit-trader

stage: prod
region: us-west-2

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts

functions:
  trade:
    handler: handler.trade

    events:
      - http:
          path: trade
          method: post

