service: coin-limit-trader

stage: prod
region: us-west-2

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamic-dotenv
  - serverless-offline-sns
  - serverless-pseudo-parameters

package:
  exclude:
    - node_modules/**/*
  include:
    handler.ts

functions:
  trade:
    handler: src/handlers/trade-api.trade
    environment:
      AWS_ACCOUNT_ID: 123456789012
    events:
      - http:
          path: trade
          method: post

  trade-scheduler:
      handler: src/handlers/trade-scheduler.trade
      events:
        - sns:
            topicName: scheduleTrade
            displayName: Schedule coin trade with limit trades

custom:
  serverless-offline-sns:
    port: 4002
    debug: true